export enum QueueJobTypes {
    CREATE_PARTICIPANT = 'CREATE_PARTICIPANT',
    UPDATE_PARTICIPANT_SCORE = 'UPDATE_PARTICIPANT_SCORE',
    CREATE_QUESTION_RESPONSE = 'CREATE_QUESTION_RESPONSE',
    UPDATE_SESSION_STATUS = 'UPDATE_SESSION_STATUS',
    CLEANUP_SESSION = 'CLEANUP_SESSION',
    NAME_CHANGE = 'NAME_CHANGE',
    UPDATE_SCREEN = 'UPDATE_SCREEN'
}